language: node_js
node_js:
  - '8.9.3'
deploy:
  provider: npm
  email: 274544338@qq.com
  api_key: YOUR_AUTH
  skip_cleanup: true
  on:
    tags: true
    branch: master
  tag: latest
  condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'